################################################################################
#
# caos-collector - CAOS collector
#
# Copyright © 2017 INFN - Istituto Nazionale di Fisica Nucleare (Italy)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
# Author: Fabrizio Chiarello <fabrizio.chiarello@pd.infn.it>
#
################################################################################

image: python:2.7

stages:
  - test

.job_template: &job_template
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install tox

test:
  <<: *job_template
  script:
    - tox -e py27

coverage:
  <<: *job_template
  script:
    - tox -e coverage
  artifacts:
    paths:
      - cover
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+\.?\d*)%/'

pep8:
  <<: *job_template
  script:
    - tox -e pep8
  allow_failure: true
